import os
print ("Non-Automated Ubuntu Auditing System")
print ("This script is provided as is with no warranties or guarantees what so ever")
print ("Created by Anthony Saldana-Valle based off CIS Ubuntu 16.04 Benchmark v1.1.0")
wait = input("PRESS ENTER TO CONTINUE...")
print("cramfs status")
os.system ("modprobe -n -v")
os.system ("install /bin/true")
os.system ("lsmod | grep cramfs")
print("There should be no output.")
print("If there is output follow the instructions below.")
print("Create the file /etc/modprobe.d/CIS.conf")
print("Add the following line'install cramfs /bin/true'")
print("run the command 'rmmod cramfs'")
wait = input("PRESS ENTER TO CONTINUE...")